syntax = "proto3";

package External_Game_Protocol;
option csharp_namespace = "GameProtocol";

message UnityGameObject {
    uint32 object_id = 1;
    uint32 object_type = 2;
    TransformInfo transform = 3;
}

message GameObjectMovementInfo {
    uint32 object_id = 1;
    TransformInfo transform = 2;
    uint32 state = 3;
}

message TransformInfo {
    Vector3 position = 1;
    oneof rotation {
        uint32 compressed_quat = 2; 
        float yaw_angle = 3;        
    }
}

message Vector3 {
    float x = 1;
    float y = 2;
    float z = 3;
}