#pragma once

enum : uint16_t {
    PKT_ID_C2D_CHANNEL_OPEN            = 0,
    PKT_ID_D2C_RESPONSE_CHANNEL_OPEN   = 1,
    PKT_ID_C2D_HEART_BEAT         = 2,
    PKT_ID_D2C_HEART_BEAT         = 3,
    PKT_ID_C2D_REQUEST_BLUEPRINT  = 4,
    PKT_ID_D2C_RESPONSE_BLUEPRINT_STATIC_OBJECTS = 5,
    PKT_ID_C2D_REQUEST_SPAWN_ME   = 6,
    PKT_ID_D2C_RESPONSE_SPAWN_ME_SPAWN_SPOT  = 7,
    PKT_ID_D2C_RESPONSE_SPAWN_ME_DYNAMIC_OBJECTS = 8,
    PKT_ID_C2D_REQUEST_SPAWN_BY_OBJECT_ID        = 9,
    PKT_ID_D2C_RESPONSE_SPAWN_BY_OBJECT_ID       = 10,
    PKT_ID_C2D_UPDATE_PLAYER_STATE               = 11,
    PKT_ID_C2D_REQUEST_SPAWN_PLAYER_OBJECTS      = 12,
    PKT_ID_D2C_SPAWN_PLAYER_OBJECT               = 13,
    PKT_ID_D2C_SPAWN_PLAYER_OBJECTS              = 14,
    PKT_ID_D2C_UPDATE_PLAYER_STATES              = 15,
    PKT_ID_C2D_NOTIFY_LOADING_COMPLETE           = 16,
    PKT_ID_D2C_FULL_INVENTORY_SYNC               = 17,
    PKT_ID_C2D_REQUEST_OPEN_CONTAINER            = 18,
    PKT_ID_D2C_RESPONSE_OPEN_CONTAINER           = 19,
    PKT_ID_C2D_CLOSE_CONTAINER                   = 20,
    PKT_ID_C2D_REQUEST_INTERACT_CONTAINER_OBJECT = 21,
    PKT_ID_D2C_RESPONSE_INTERACT_CONTAINER_OBJECT = 22,
    PKT_ID_C2D_REQUEST_EQUIP_ITEM                = 23,
    PKT_ID_D2C_RESPONSE_EQUIP_ITEM               = 24,
    PKT_ID_D2C_RESPONSE_INTERACT_CONTAINER_OBJECT_DENY = 25,
    PKT_ID_D2C_RESPONSE_EQUIP_ITEM_DENY               = 26,
    PKT_ID_C2D_REQUEST_RECENT_INVENTORY_INFO           = 27,
    PKT_ID_D2C_RESPONSE_RECENT_CONTAINER_INFO          = 28,
    PKT_ID_C2D_REQUEST_WEAPON_FIRE                     = 29,
    PKT_ID_D2C_BROADCAST_WEAPON_FIRE                   = 30,
    PKT_ID_D2C_NOTIFY_HEALTH_CHANGE                    = 31,
    PKT_ID_C2D_REQUEST_RECALL                          = 32,
    PKT_ID_D2C_RESPONSE_RECALL                         = 33,
    PKT_ID_D2C_NOTIFY_RECALL_RESULT                    = 34,
    PKT_ID_D2C_DESPAWN_PLAYER_OBJECT                   = 35,
    PKT_ID_D2C_NOTIFY_SPAWN_OBJECT                     = 36,
    PKT_ID_D2C_NOTIFY_WEAPON_CHANGED                   = 37,
    PKT_ID_C2D_REQUEST_SWITCH_WEAPON                   = 38,
    PKT_ID_D2C_NOTIFY_DESPAWN_OBJECT                   = 39,
    PKT_ID_D2C_NOTIFY_PLAYER_KILLED                    = 40,
    PKT_ID_D2C_NOTIFY_OBJECT_KILLED                    = 41,
    PKT_ID_C2D_REQUEST_RELOAD                          = 42,
    PKT_ID_D2C_RESPONSE_RELOAD                         = 43,
    PKT_ID_C2D_NOTIFY_RELOAD_SEQUENCE                  = 44,
    PKT_ID_D2C_NOTIFY_RELOAD_SEQUENCE                  = 45,
    PKT_ID_MAX                                         = 46,
};

// 아이템 조작 거부 사유 비트
enum DenyReason : uint32_t {
    DENY_VERSION_MISMATCH        = 0x0001,
    DENY_SLOT_EMPTY              = 0x0002,
    DENY_SLOT_NOT_EMPTY          = 0x0004,
    DENY_SLOT_ALREADY_EMPTY      = 0x0008,
    DENY_INVALID_QUANTITY        = 0x0010,
    DENY_BLUEPRINT_MISMATCH      = 0x0020,
    DENY_ITEM_TYPE_MISMATCH      = 0x0040,
    DENY_BARE_HANDED             = 0x0080,
    DENY_MAGAZINE_UNLOAD_FAILED  = 0x0100,
    DENY_SERVER_INTERNAL         = 0x0200,
};